db:
  mysql:
    # url: "root:root@tcp(webook-mysql-service:3308)/webook"
    url: "root:root@tcp(192.168.2.130:13306)/webook"
    # migrationUrl: "mysql://root:root@tcp(webook-mysql-service:3308)/webook"
    migrationUrl: "mysql://root:root@tcp(192.168.2.130:13306)/webook"
    migrationSourceUrl: "file://db/migration"

etcd:
  endpoints:
    - "192.168.2.130:12379"

kafka:
  address:
    - "localhost:9094"

http:
  address: ":8070"

grpc:
  server:
    port: 8092
    name: "payment"
    ttl: 60

