db:
  mysql:
    # url: "root:root@tcp(webook-mysql-service:3308)/webook"
    url: "root:root@tcp(192.168.2.130:13306)/webook"
    # migrationUrl: "mysql://root:root@tcp(webook-mysql-service:3308)/webook"
    migrationUrl: "mysql://root:root@tcp(192.168.2.130:13306)/webook"
    migrationSourceUrl: "file://db/migration"

etcd:
  endpoints:
    - "192.168.2.130:12379"

redis:
  address: ""

kafka:
  address:
    - "localhost:9094"

grpc:
  server:
    port: 8093
    name: "reward"
    ttl: 60
  client:
    payment:
      target: "etcd:///service/payment"
    account:
      target: "etcd:///service/account"
