// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Anwenya/GeekTime/webook/comment/grpc"
	"github.com/Anwenya/GeekTime/webook/comment/ioc"
	"github.com/Anwenya/GeekTime/webook/comment/repository"
	"github.com/Anwenya/GeekTime/webook/comment/repository/dao"
	"github.com/Anwenya/GeekTime/webook/comment/service"
	"github.com/Anwenya/GeekTime/webook/pkg/grpcx"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	commentDAO := dao.NewCommentGORMDAO(db)
	commentRepository := repository.NewCommentRepository(commentDAO, loggerV1)
	commentService := service.NewCommentService(commentRepository, loggerV1)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	client := ioc.InitEtcdClient(loggerV1)
	server := ioc.InitGrpcxServer(commentServiceServer, client, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

type App struct {
	server *grpcx.Server
}
