// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Anwenya/GeekTime/webook/internal/ioc"
	"github.com/Anwenya/GeekTime/webook/internal/repository"
	"github.com/Anwenya/GeekTime/webook/internal/repository/cache"
	"github.com/Anwenya/GeekTime/webook/internal/repository/dao"
	"github.com/Anwenya/GeekTime/webook/internal/service"
	"github.com/Anwenya/GeekTime/webook/internal/web"
	"github.com/gin-gonic/gin"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	config := ioc.InitConfig()
	cmdable := ioc.InitRedis(config)
	maker := ioc.InitTokenMaker(config)
	v := ioc.InitGinMiddlewares(cmdable, config, maker)
	db := ioc.InitDB(config)
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	smService := ioc.InitSMSService()
	codeService := service.NewCodeService(codeRepository, smService)
	userHandler := web.NewUserHandler(userService, codeService, config, maker)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
