// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Anwenya/GeekTime/webook/interactive/events"
	"github.com/Anwenya/GeekTime/webook/interactive/grpc"
	"github.com/Anwenya/GeekTime/webook/interactive/ioc"
	"github.com/Anwenya/GeekTime/webook/interactive/repository"
	"github.com/Anwenya/GeekTime/webook/interactive/repository/cache"
	"github.com/Anwenya/GeekTime/webook/interactive/repository/dao"
	"github.com/Anwenya/GeekTime/webook/interactive/service"
	"github.com/Anwenya/GeekTime/webook/pkg/grpcx"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.NewGrpcxServer(interactiveServiceServer)
	client := ioc.InitSaramaClient()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(interactiveRepository, client, loggerV1)
	historyDao := dao.NewGORMHistoryDAO(db)
	readHistoryRepository := repository.NewCachedReadHistoryRepository(historyDao)
	historyRecordConsumer := events.NewHistoryRecordConsumer(readHistoryRepository, client, loggerV1)
	v := ioc.InitConsumers(interactiveReadEventConsumer, historyRecordConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

type App struct {
	server    *grpcx.Server
	consumers []events.Consumer
}

var thirdPartySet = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitSaramaClient, ioc.InitRedis)

var interactiveServiceSet = wire.NewSet(cache.NewRedisInteractiveCache, dao.NewGORMInteractiveDAO, repository.NewCachedInteractiveRepository, service.NewInteractiveService)

var historySet = wire.NewSet(dao.NewGORMHistoryDAO, repository.NewCachedReadHistoryRepository)
