// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Anwenya/GeekTime/webook/payment/grpc"
	"github.com/Anwenya/GeekTime/webook/payment/ioc"
	"github.com/Anwenya/GeekTime/webook/payment/repository"
	"github.com/Anwenya/GeekTime/webook/payment/repository/dao"
	"github.com/Anwenya/GeekTime/webook/payment/web"
	"github.com/Anwenya/GeekTime/webook/pkg/ginx"
	"github.com/Anwenya/GeekTime/webook/pkg/grpcx"
)

// Injectors from wire.go:

func Init() *App {
	wechatConfig := ioc.InitWechatConfig()
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	loggerV1 := ioc.InitLogger()
	client := ioc.InitWechatClient(wechatConfig, loggerV1)
	db := ioc.InitDB(loggerV1)
	paymentDAO := dao.NewPaymentGORMDAO(db)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	saramaClient := ioc.InitKafka(loggerV1)
	producer := ioc.InitProducer(saramaClient)
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, wechatConfig, producer, loggerV1)
	wechatHandler := web.NewWechatHandler(handler, nativePaymentService, loggerV1)
	server := ioc.InitGinServer(wechatHandler)
	wechatServiceServer := grpc.NewWechatServiceServer(nativePaymentService)
	clientv3Client := ioc.InitEtcdClient(loggerV1)
	grpcxServer := ioc.InitGrpcxServer(wechatServiceServer, clientv3Client, loggerV1)
	app := &App{
		WebServer:  server,
		GRPCServer: grpcxServer,
	}
	return app
}

// wire.go:

type App struct {
	GRPCServer *grpcx.Server
	WebServer  *ginx.Server
}
