// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Anwenya/GeekTime/webook/follow/grpc"
	"github.com/Anwenya/GeekTime/webook/follow/ioc"
	"github.com/Anwenya/GeekTime/webook/follow/repository"
	"github.com/Anwenya/GeekTime/webook/follow/repository/cache"
	"github.com/Anwenya/GeekTime/webook/follow/repository/dao"
	"github.com/Anwenya/GeekTime/webook/follow/service"
	"github.com/Anwenya/GeekTime/webook/pkg/grpcx"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followDao := dao.NewFollowGORMDAO(db)
	cmdable := ioc.InitRedis(loggerV1)
	followCache := cache.NewFollowRedisCache(cmdable)
	followRepository := repository.NewFollowRepository(followDao, followCache, loggerV1)
	followService := service.NewFollowService(followRepository)
	followServiceServer := grpc.NewFollowServiceServer(followService)
	client := ioc.InitEtcdClient(loggerV1)
	server := ioc.InitGrpcxServer(followServiceServer, client, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

type App struct {
	server *grpcx.Server
}
